-- 2026-06-06: Operator onboarding rework (S05).
-- 1) Operator gains application-form profile fields (brandName, contactName, address, routesSummary).
-- 2) OperatorUser gains `username` — the new login key (was phone). Generated by admin provisioning
--    as BRAND_ACRONYM-last4phone; phone becomes contact-only.
-- Username is added nullable, backfilled for existing rows (so the NOT NULL + UNIQUE hold), then
-- constrained. Backfill uses the row id to guarantee uniqueness for pre-existing seed/test rows;
-- re-provisioned/seeded operators receive real BRAND_ACRONYM-last4phone usernames.

ALTER TABLE "Operator" ADD COLUMN "brandName" TEXT;
ALTER TABLE "Operator" ADD COLUMN "contactName" TEXT;
ALTER TABLE "Operator" ADD COLUMN "address" TEXT;
ALTER TABLE "Operator" ADD COLUMN "routesSummary" TEXT;

ALTER TABLE "OperatorUser" ADD COLUMN "username" TEXT;

-- Backfill existing rows with a guaranteed-unique placeholder login key.
UPDATE "OperatorUser" SET "username" = 'op-' || "id" WHERE "username" IS NULL;

ALTER TABLE "OperatorUser" ALTER COLUMN "username" SET NOT NULL;

CREATE UNIQUE INDEX "OperatorUser_username_key" ON "OperatorUser"("username");
