# Safe-delete script — generated by /dead-code-scan 2026-06-05 (PR #7)
# REVIEW BEFORE RUNNING. Contains only P1 (0-importer) candidates.
# These are RECENT rebuild additions — confirm each is NOT a pending-wire feature first.
# Run from repo root:  powershell -ExecutionPolicy Bypass -File scripts\safe-delete-2026-06-05.ps1

$ErrorActionPreference = 'Stop'

$targets = @(
  'components/op/KpiTile.tsx',       # 0 importers — op-console redesign leftover
  'components/op/DetailLayout.tsx',  # 0 importers — no consumer
  'lib/catalog/updatePickupPoint.ts' # 0 importers — UNWIRED service: prefer WIRE over delete; confirm intent
)

foreach ($t in $targets) {
  if (-not (Test-Path $t)) { Write-Host "SKIP (missing): $t"; continue }
  $ans = Read-Host "Delete $t ? (y/N)"
  if ($ans -eq 'y') {
    git rm $t
    Write-Host "Deleted: $t"
  } else {
    Write-Host "Kept: $t"
  }
}

Write-Host ""
Write-Host "Done. Re-run 'pnpm tsc --noEmit' + 'pnpm lint' before committing."
Write-Host "NOTE: lib/catalog/updatePickupPoint.ts may deserve an issue to WIRE it, not delete it."
